name: change_case
description: An extension on String for the missing methods for camelCase, PascalCase, Capital Case, snake_case, param-case, CONSTANT_CASE and others.
version: 2.0.1
repository: https://github.com/mrgnhnt96/change_case
homepage: https://github.com/mrgnhnt96/change_case
topics:
  - formatting
  - case
  - casing
  - camelcase
  - snakecase

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ">=1.7.0 <2.0.0"

dev_dependencies:
  test: ^1.24.9
  very_good_analysis: ^5.1.0
