name: change_case
description: An extension on String to transform a string between camelCase, PascalCase, Capital Case, snake_case, param-case, CONSTANT_CASE and others.
version: 1.0.1
repository: https://github.com/mrgnhnt96/change_case
homepage: https://github.com/mrgnhnt96/change_case

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  derry: ^1.4.3
  test: ">=1.17.0 <1.18.0"
  very_good_analysis: ^2.3.0

scripts: derry.yaml
