name: change_case
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ">=1.17.0 <1.18.0"
  very_good_analysis: ^2.3.0
